[phases.setup]
nixPkgs = ["wget", "unzip"]

[phases.build]
cmds = [
  "wget https://github.com/pocketbase/pocketbase/releases/download/v0.22.21/pocketbase_0.22.21_linux_amd64.zip",
  "unzip pocketbase_0.22.21_linux_amd64.zip",
  "chmod +x pocketbase",
  "rm pocketbase_0.22.21_linux_amd64.zip",
  "chmod +x start.sh",
  "mkdir -p pb_data"
]

[start]
cmd = "./start.sh"
